language: node_js
node_js:
  - 0.1
deploy:
  - provider: npm
    email: andrei.shostik@gmail.com
    on:
      branch: master
      tags: true
before_script:
  - npm install
script:
  - grunt karma-main